project_id = "gzlwkvmivbfcvczoqphq"

[functions.deduct-tokens]
verify_jwt = true

[functions.generate-content]
verify_jwt = true

[functions.cleanup-stuck-generations]
verify_jwt = false

[functions.kie-ai-webhook]
verify_jwt = false

[functions.fix-stuck-generation]
verify_jwt = false

[functions.create-dodo-payment]
verify_jwt = true

[functions.dodo-payments-webhook]
verify_jwt = false