project_id = "gzlwkvmivbfcvczoqphq"

[functions.cancel-render]
verify_jwt = true

[functions.store-vault-secret]
verify_jwt = true

[functions.kie-ai-webhook]
verify_jwt = false

[functions.json2video-webhook]
verify_jwt = false

[functions.dodo-payments-webhook]
verify_jwt = false

[functions.dodo-webhook-v2]
verify_jwt = false
